# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039e885c557b934a67e1fe8186402fa182a73e3c70153e4b56dba89acf32e251b8b4e6df4b321b795970dd965961d94789f6572333f3c0799ecbe9a184eac49d

test:
  secret_key_base: 3eb604f8dd2eecc7443a82724ccad796b06a12ca9b16c42e8d0ad1c97f1e73d57215b96eb8248f785e7de5644de351aa164afcd5cf6b67e046801b38cabbe61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
